const globalConstants = {
  CHANGE_ACTUAL_EVENT: 'CHANGE_ACTUAL_EVENT',
  CHANGE_ACTUAL_GROUP: 'CHANGE_ACTUAL_GROUP',
  CHANGE_TITLE: 'CHANGE_TITLE',
  GET_EVENTSGROUPS_FAILURE: 'GET_EVENTSGROUPS_FAILURE',
  GET_EVENTSGROUPS_SUCCESS: 'GET_EVENTSGROUPS_SUCCESS',

};

export default globalConstants;
