const groupConstants = {
  GROUP_GET_ALL: 'GROUP_GET_ALL',
  GROUP_GET_ALL_FAILURE: 'GROUP_GET_ALL_FAILURE',
  GROUP_GET_ALL_SUCCESS: 'GROUP_GET_ALL_SUCCESS',
  GROUP_GET_INFOS_FAILURE: 'GROUP_GET_INFOS_FAILURE',
  GROUP_GET_INFOS_SUCCESS: 'GROUP_GET_INFOS_SUCCESS',
};

export default groupConstants;
