const guestConstants = {
  GUEST_GET_ALL: 'GUEST_GET_ALL',
  GUEST_GET_ALL_FAILURE: 'GUEST_GET_ALL_FAILURE',
  GUEST_GET_ALL_SUCCESS: 'GUEST_GET_ALL_SUCCESS',

  LOGIN_REQUEST: 'GUEST_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'GUEST_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'GUEST_LOGIN_FAILURE',

  LOGOUT: 'GUEST_LOGOUT',
};

export default guestConstants;
